fullnameOverride: monitoring
namespaceOverride: monitoring

defaultRules:
  create: false

alertmanager:
  serviceMonitor:
    selfMonitor: false

coreDns:
  serviceMonitor:
    enabled: false

kubeEtcd:
  serviceMonitor:
    enabled: false

kubeScheduler:
  serviceMonitor:
    enabled: false

kubeProxy:
  serviceMonitor:
    enabled: false

kubeControllerManager:
  serviceMonitor:
    enabled: false

kubeApiServer:
  enabled: false

kubeStateMetrics:
  enabled: false

kubelet:
  enabled: false