###################
## Default rules ##
###################
defaultRules:
  create: false

###############################################################
## Configuration Node Exporter as DaemonSet to all K8s nodes ##
###############################################################
nodeExporter:
  enabled: true
  operatingSystems:
    linux:
      enabled: true
    aix:
      enabled: true
    darwin:
      enabled: true

prometheus-node-exporter:
  prometheus:
    monitor:
      enabled: false

#############################################################################
## Configuration Operator to manage Prometheus and Alertmanager components ##
#############################################################################
prometheusOperator:
  enabled: true

  serviceMonitor:
    selfMonitor: false

##################################
## Configuration for Prometheus ##
##################################
prometheus:
  enabled: true

  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
  prometheusSpec:
    ## Interval between consecutive scrapes (Default 30s)
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/release-0.44/pkg/prometheus/promcfg.go#L180-L183
    scrapeInterval: "15s"

  serviceMonitor:
    selfMonitor: false

####################################
## Configuration for AlertManager ##
####################################
alertmanager:
  enabled: false

###############################
## Configuration for Grafana ##
###############################
grafana:
  enabled: false

###################################
## Configuration for K8s metrics ##
###################################
kubeStateMetrics:
  enabled: false

## Component for scraping the K8s API server
kubeApiServer:
  enabled: false

## Component for scraping the K8s kubelet and kubelet-hosted cAdvisor
kubelet:
  enabled: false

## Component for scraping K8s CoreDns
coreDns:
  enabled: false

## Component for scraping K8s Controller Manager
kubeControllerManager:
  enabled: false

## Component for scraping K8s Etcd
kubeEtcd:
  enabled: false

## Component for scraping K8s Scheduler
kubeScheduler:
  enabled: false

## Component for scraping K8s proxy
kubeProxy:
  enabled: false
