################################################
## Configuration for Grafana Mimir Parameters ##
################################################
mimir:
  structuredConfig:
    limits:
      ## Enforcing storage retention 3 months
      ## Ref: https://grafana.com/docs/mimir/latest/configure/configure-metrics-storage-retention/
      compactor_blocks_retention_period: 90d

      ## Tuning for split-and-merge compaction algorithm
      ## Recommendation: 1 shard per every 8 million active series in a tenant
      ## Ref: https://grafana.com/docs/mimir/latest/references/architecture/components/compactor/#compaction-algorithm
      compactor_split_groups: 2
      compactor_split_and_merge_shards: 1

    compactor:
      ## Enforcing time range for hard deletion
      ## Ref: https://grafana.com/docs/mimir/latest/references/architecture/components/compactor/#blocks-deletion
      deletion_delay: 1h

      ## Configure time for Compactor running blocks cleanup and maintenance, as well as update the bucket index
      ## Ref: https://grafana.com/docs/mimir/latest/references/architecture/bucket-index/#how-it-gets-updated
      cleanup_interval: 10m

    blocks_storage:
      bucket_store:
        ## Configure time for Querier to scan the bucket, or to refresh the bucket index if enable
        ## Ref: https://grafana.com/docs/mimir/latest/references/architecture/bucket-index/#how-its-used-by-the-querier
        sync_interval: 10m
      

#############################
## Configuration for Ruler ##
#############################
ruler:
  enabled: false

####################################
## Configuration for Alertmanager ##
####################################
alertmanager:
  enabled: false

##########################################
## Configuration for Overrides Exporter ##
##########################################
overrides_exporter:
  enabled: false

#######################################
## Configuration for Query Scheduler ##
#######################################
query_scheduler:
  enabled: false