###################################
## Configuration for Distributor ##
###################################
distributor:
  replicas: 3

#############################
## Configuration for Ruler ##
#############################
ruler:
  enabled: false

####################################
## Configuration for Alertmanager ##
####################################
alertmanager:
  enabled: false

##########################################
## Configuration for Overrides Exporter ##
##########################################
overrides_exporter:
  enabled: false

#######################################
## Configuration for Query Scheduler ##
#######################################
query_scheduler:
  enabled: false